const calendar=document.querySelector('#calendar'),monthLabel=document.querySelector('#month-label'),timeSlots=document.querySelector('#time-slots'),timeTitle=document.querySelector('#time-title'),summary=document.querySelector('#selection-summary');
let shown=new Date();shown.setDate(1);let chosenDate=null,chosenTime=null,consultationType='개인 상담',consultationPrice='100,000원',blocked={},availabilityError='';const loadedMonths=new Set(),loadingMonths=new Set();
const pad=n=>String(n).padStart(2,'0'),key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,koreanDate=d=>`${d.getMonth()+1}월 ${d.getDate()}일 (${['일','월','화','수','목','금','토'][d.getDay()]})`;
function monthRange(date){const start=new Date(date.getFullYear(),date.getMonth(),1),end=new Date(date.getFullYear(),date.getMonth()+1,0);return{start:key(start),end:key(end),id:`${start.getFullYear()}-${pad(start.getMonth()+1)}`}}
async function loadAvailability(date=shown){const{start,end,id}=monthRange(date);if(loadedMonths.has(id)||loadingMonths.has(id))return;loadingMonths.add(id);availabilityError='';renderTimes();try{const response=await fetch(`/api/availability?start=${encodeURIComponent(start)}&end=${encodeURIComponent(end)}`),result=await response.json();if(!response.ok)throw new Error(result.error||'예약 가능 시간을 불러오지 못했습니다.');Object.entries(result.blocked||{}).forEach(([day,slots])=>{blocked[day]=[...new Set(slots)]});loadedMonths.add(id)}catch(error){availabilityError=error.message||'예약 가능 시간을 불러오지 못했습니다.'}finally{loadingMonths.delete(id);renderTimes()}}
function isSelectedMonthLoading(){return chosenDate&&loadingMonths.has(monthRange(chosenDate).id)}
function renderCalendar(){calendar.innerHTML='';monthLabel.textContent=`${shown.getFullYear()}년 ${shown.getMonth()+1}월`;const today=new Date();today.setHours(0,0,0,0);const start=new Date(shown.getFullYear(),shown.getMonth(),1),end=new Date(shown.getFullYear(),shown.getMonth()+1,0);for(let i=0;i<start.getDay();i+=1)calendar.insertAdjacentHTML('beforeend','<span></span>');for(let day=1;day<=end.getDate();day+=1){const date=new Date(shown.getFullYear(),shown.getMonth(),day),isSunday=date.getDay()===0,isTodayOrPast=date<=today,button=document.createElement('button');button.textContent=day;button.disabled=isSunday||isTodayOrPast;if(isSunday)button.className='sunday';if(chosenDate&&key(date)===key(chosenDate))button.classList.add('selected');button.addEventListener('click',()=>{chosenDate=date;chosenTime=null;renderCalendar();renderTimes();updateSummary();loadAvailability(date)});calendar.append(button)}}
function renderTimes(){timeSlots.innerHTML='';if(!chosenDate){timeTitle.textContent='날짜를 먼저 선택해 주세요';return}if(isSelectedMonthLoading()){timeTitle.textContent='예약 가능 시간을 확인하고 있습니다…';return}if(availabilityError&&!loadedMonths.has(monthRange(chosenDate).id)){timeTitle.textContent=availabilityError;return}timeTitle.textContent=`${koreanDate(chosenDate)} · 60분 상담`;const unavailable=blocked[key(chosenDate)]||[];for(let hour=10;hour<19;hour+=1){const time=`${pad(hour)}:00`,button=document.createElement('button');button.textContent=`${time} — ${pad(hour+1)}:00`;button.disabled=unavailable.includes(time);if(chosenTime===time)button.classList.add('selected');button.addEventListener('click',()=>{chosenTime=time;renderTimes();updateSummary()});timeSlots.append(button)}}
function updateSummary(){summary.textContent=chosenDate&&chosenTime?`${consultationType} · ${consultationPrice} · ${koreanDate(chosenDate)} ${chosenTime}–${pad(Number(chosenTime.slice(0,2))+1)}:00`:'상담 종류와 시간을 선택해 주세요.'}
document.querySelectorAll('.type-option').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.type-option').forEach(item=>item.classList.remove('selected'));button.classList.add('selected');consultationType=button.dataset.type;consultationPrice=button.dataset.price;updateSummary()}));
document.querySelector('#previous-month').addEventListener('click',()=>{shown.setMonth(shown.getMonth()-1);renderCalendar();loadAvailability()});document.querySelector('#next-month').addEventListener('click',()=>{shown.setMonth(shown.getMonth()+1);renderCalendar();loadAvailability()});
document.querySelector('#booking-form').addEventListener('submit',async event=>{event.preventDefault();if(!chosenDate||!chosenTime){summary.textContent='날짜와 시간을 모두 선택해 주세요.';return}const selectedKey=key(chosenDate);if((blocked[selectedKey]||[]).includes(chosenTime)){summary.textContent='방금 다른 예약이 접수된 시간입니다. 다른 시간을 선택해 주세요.';renderTimes();return}const form=event.target,submit=form.querySelector('[type="submit"]'),data=new FormData(form),payload={type:consultationType,date:selectedKey,time:chosenTime,bookerName:data.get('bookerName'),bookerPhone:data.get('bookerPhone'),visitorName:data.get('visitorName'),visitorPhone:data.get('visitorPhone'),message:data.get('message')};submit.disabled=true;submit.textContent='예약을 확인하고 있습니다…';try{const response=await fetch('/api/reservations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw new Error(result.error||'예약을 처리하지 못했습니다.');(blocked[selectedKey]??=[]).push(chosenTime);document.querySelector('#success-copy').textContent=`${payload.bookerName}님, ${consultationType} (${consultationPrice} · ${koreanDate(chosenDate)} ${chosenTime}) 예약이 접수되었습니다.`;document.querySelector('#success-dialog').showModal();form.reset();chosenTime=null;renderTimes();updateSummary()}catch(error){summary.textContent=error.message||'예약 처리 중 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.';await loadAvailability(chosenDate)}finally{submit.disabled=false;submit.textContent='예약 요청하기'}});
document.querySelector('#close-success').addEventListener('click',()=>document.querySelector('#success-dialog').close());renderCalendar();renderTimes();updateSummary();loadAvailability();
